name: flutter_instaclone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_icons: ^1.1.0
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 # path_provider: ^2.0.11
  firebase_core: ^1.21.0
  firebase_auth: ^3.7.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
